### ISSUE TITLE
Problem with navbar dropdown on a desktop 

### ISSUE THREAD

**Issue by rackowsky** [maroon-studio/maroon-studio#20]
When I'm opening navbar dropdown on desktop, everything is fine, when I'm closing by the same button I opened it with, It's also fine, but when I'm trying to close this by clicking outside this navbar **it isn't work**.

<img width="578" alt="image" src="https://github.com/maroon-studio/maroon-studio/assets/73818700/f0085275-f2a4-47d0-838a-7a38889281cd">

**Comment by mariampolski** [comment]
Problem solved @rackowsky.
